### ISSUE TITLE
Group posts together by competition

### ISSUE THREAD

**Issue by jvstrange** [b0tchsec/b0tchsec.github.io#3]
Our _posts folder will quickly become unruly if we keep adding everything right in there in order. We should consider subfolders, maybe in the structure of "2016/sctfq1/post.md" and "2016/GoogleCTF/post.md" for instance. Open to suggestions, just something to better organize that folder.

**Comment by aagallag** [comment]
_posts/{year}/{competition}/{chall}/post.md

or....

_posts/{competition}/{year}/{chall}/post.md

?

**Comment by jvstrange** [comment]
If we do _posts/{year}/{competition}/challenge.md that could enable us to have a page for _posts/{year}/index.md and _posts/{year}/{competition}/index.md in which we show all the posts for that year or for that challenge. I think having competition on the top the hierarchy could result in a lot of top level folders, many with only a few (or one) sub folder.

**Comment by aagallag** [comment]
Agreed!

**Comment by jvstrange** [comment]
Closing issue for now. All posts are going into _posts directly using old file format, but permalinks have been updated to use :year/:categories/:title, where :title is being overridden by the slug front-matter. So be sure to set your categories: and slug: front matter!
