### ISSUE TITLE
Markdown not converted correctly

### ISSUE THREAD

**Issue by Ri1a** [b0tchsec/b0tchsec.github.io#3]
Hi! I love your jekyll-clean theme!

Now I am encountering to a problem:

I want to add markdown sites, but not as _posts, just as sites. The folder with the .md file is located at /writeups/. But it's not formed correctly...

Here's the webpage:
![markdown_1](https://user-images.githubusercontent.com/32012280/44106043-c8a8b88a-9ff3-11e8-9b85-ec4fde8f1fa1.png)

And here's a code snippet:
```
---
layout: page
title: Writeup's
permalink: /writeups/
---

Writeup's will be published in english! It may appear that the textstyle differs from other texts.

## Hacking Series

<a href="{{ site.baseurl }}/writeups/bwapp">bWAPP - buggy web app</a>

<a href="{{ site.baseurl }}/writeups/hackthebox">HackTheBox</a>
```

I want that it looks like a post, but not that it's a post:D

You have an idea?

**Comment by 0xdade** [comment]
Did you get this figured out? I just saw it unfortunately. I haven't done much with our site in quite a while so don't remember exactly how to do certain things :)

**Comment by Ri1a** [comment]
So, I was able to upload the entire project thinking I solved the problem. But when you browse now to [https://shadow2xx.github.io/](https://shadow2xx.github.io/) it's not converted correcty. Any ideas?

**Comment by ajacques** [comment]
If you're trying to fix the CSS, it seems to be related to this: https://github.com/Shadow2xx/shadow2xx.github.io/blob/master/_config.yml#L7-L13

You reference: `/jekyll-clean/css/syntax.css` for CSS, but the CSS is actually compiled to `https://shadow2xx.github.io/css/syntax.css`.

Is your goal to have the entire site mounted under `/jekyll-clean/*`?

**Comment by Shadow2xx** [comment]
No, just under https://shadow2xx.github.io/

**Comment by Ri1a** [comment]
Changed the url and now it works! Thanks alot!
